---
title: "ACURÁCIA E VARIABILIDADE DE MÉTODOS DE AMOSTRAGEM DE ENXURRADA"
author: "Alessandro Samuel-Rosa^1^, Jean Michel Moura-Bueno^2^, Ricardo Simão Diniz Dalmolin^3^"
output: 
  bookdown::word_document2:
    reference_docx: template.docx
lang: pt
editor_options: 
  chunk_output_type: inline
---

```{r, eval=FALSE, echo=FALSE}
rmarkdown::render('author.Rmd', encoding = 'UTF-8', output_dir = "../docs")
```

^1^* Pós-doutorando em Ciência do Solo, Programa de Pós-Graduação em Ciência do Solo, Universidade Federal de
Santa Maria, Santa Maria, RS. E-mail: alessandrosamuelrosa@gmail.com (autor para correspondência).

^2^ Doutorando em Ciência do Solo, Programa de Pós-Graduação em Ciência do Solo, Universidade Federal de Santa 
Maria, Santa Maria, RS. E-mail: buenojean1@gmail.com.

^3^ Professor Adjunto, Departamento de Solos, Universidade Federal de Santa Maria, Santa Maria, RS. E-mail: 
dalmolin@ufsm.br.

**Contribuição dos autores**

ASR: Conceptualization, Data Curation, Formal Analysis, Investigation, Methodology, Project Administration,
Software, Validation, Visualization, Writing – Original Draft Preparation.

JMMB: Data Curation, Investigation, Visualization, Writing – Review & Editing.

RSDD: Funding Acquisition, Resources, Supervision, Writing – Review & Editing.

Baseado em http://journals.plos.org/plosone/s/authorship
